import './Home.css';

const Home = () => {
	return (
		<div className="home-container">
			<div className="background-section">
				<section className="section">
					<div className="text">
						<h2>Purpose of this page</h2>
						<p>
							This page is designed to demonstrate the incredible power of modern AI tools. Using
							GitHub Copilot alongside ChatGPT, this site was built efficiently and creatively,
							showcasing how AI can assist developers in writing clean, effective code and
							streamline the development process. It serves as an example of the future of web
							development, where AI and human collaboration come together to create meaningful
							projects faster than ever.
						</p>
					</div>
				</section>

				<section className="section reverse">
					<div className="text">
						<h2>Who am I?</h2>
						<p>
							I am a somewhat lazy software engineer who values efficiency and utility over
							complexity. My goal is to create useful web services that genuinely help people,
							while minimizing repetitive work by leveraging automation and AI tools. Hosting
							projects on the web allows me to share my work with a broad audience, making my
							efforts accessible to anyone, anywhere. This balance between laziness and
							productivity often leads to surprisingly powerful and practical results.
						</p>
					</div>
				</section>

				<section className="section reverse">
					<div className="text">
						<h2>Future plan</h2>
						<p>
							In the future, this website aims to expand its offerings by providing a wider range of open-source tools 
							designed to be both practical and accessible for everyday use. Alongside these tools, the site will introduce 
							a selection of simple, entertaining games to offer visitors a fun and interactive experience. While some ideas 
							are still taking shape (and maybe haven't quite come to mind yet :D), the overall vision is to continually grow 
							and evolve with new and creative additions—
							<em>if I'm available and in a good mood to do this</em>, of course! Stay tuned—there's more to come!
						</p>
						<p>(Even the texts are generated by AI!)</p>
					</div>
				</section>
			</div>

			<section className="section memes">
				<h2>Some memes</h2>
				<div className="memes-container">
					<img src={`${process.env.PUBLIC_URL}/assets/tomori.jpeg`} alt="Meme 1" className="meme-image" />
					<img src={`${process.env.PUBLIC_URL}/assets/ishoni.jpeg`} alt="Meme 2" className="meme-image" />
				</div>
			</section>
		</div>
	);
};

export default Home;